### ISSUE TITLE
Credentials stored in repositories in plain text are a security risk

### ISSUE THREAD

**Issue by hgascon** [gecio/gecio.github.io#177]
In the following snippet, customers are suggested to store their credentials in plain text in their repositories. This is a security risk. If someone get access to the repository, the IP of the application or service configured in the DNS could be changed and the service spoofed.
https://github.com/gecio/gecio.github.io/blob/f64f77b04715527dcf327aac817214461a0c8481/docs/_gks/k8sapplications/externaldnsanddesignate/index.de.md?plain=1#L156-L159

**Comment by qeqar** [comment]
As this is only the example code and we don't say anything about saving or even use that outside any test, we see that as a non issue.
