### ISSUE TITLE
Possibility to add usecases

### ISSUE THREAD

**Issue by YojanaGadiya** [gecio/gecio.github.io#199]
Dear GEC team,

It is possible to add more use cases on how to spin up VMs and use them externally. For, e.g. spinning up a docker environment in the VM and exposing it? Or does it allow for installing some software like KNIME and Jupyter notebooks and allowing access to users?

Regards,
Yojana Gadiya

**Comment by kbudde** [comment]
Hello @YojanaGadiya,
Thank you for your inquiry. 
Currently, we do not offer quick start guides for user workloads on Virtual Machines. Our service is limited to provisioning VMs without internal services.
However, there are numerous quick start tutorials available that may be of help. Should you wish to contribute something valuable, we welcome a merge request to our documentation.

Please be aware: We are in the process of transitioning to a new documentation repository at https://github.com/wiit-cloud/docs and https://docs.wiit-cloud.io/.
The current repository will soon be phased out. For further inquiries, please submit a ticket through our standard support channels.

Best regards,

Kris Budde
